CREATE TABLE "budget-gamer-next_articles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "budget-gamer-next_articles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text NOT NULL,
	"cover" text NOT NULL,
	"link" text NOT NULL,
	"domain" text NOT NULL,
	"start_date" timestamp with time zone NOT NULL,
	"end_date" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "budget-gamer-next_free_games" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "budget-gamer-next_free_games_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"cover" text NOT NULL,
	"cover_portrait" text NOT NULL,
	"description" text NOT NULL,
	"developer" text NOT NULL,
	"start_date" timestamp with time zone,
	"end_date" timestamp with time zone,
	"free" boolean,
	"platform_ids" text[],
	"provider_id" text NOT NULL,
	"provider_url" text NOT NULL,
	"publisher" text NOT NULL,
	"release_date" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "budget-gamer-next_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "budget-gamer-next_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "budget-gamer-next_subscription_games" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "budget-gamer-next_subscription_games_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"cover" text NOT NULL,
	"cover_portrait" text NOT NULL,
	"description" text NOT NULL,
	"developer" text NOT NULL,
	"start_date" timestamp with time zone,
	"end_date" timestamp with time zone,
	"platform_ids" text[],
	"provider_id" text NOT NULL,
	"provider_url" text NOT NULL,
	"publisher" text NOT NULL,
	"release_date" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "articles_title_idx" ON "budget-gamer-next_articles" USING btree ("title");--> statement-breakpoint
CREATE INDEX "articles_createdAt_idx" ON "budget-gamer-next_articles" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "free_games_name_idx" ON "budget-gamer-next_free_games" USING btree ("name");--> statement-breakpoint
CREATE INDEX "free_games_start_date_idx" ON "budget-gamer-next_free_games" USING btree ("start_date");--> statement-breakpoint
CREATE INDEX "free_games_end_date_idx" ON "budget-gamer-next_free_games" USING btree ("end_date");--> statement-breakpoint
CREATE INDEX "post_name_idx" ON "budget-gamer-next_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "subscription_games_name_idx" ON "budget-gamer-next_subscription_games" USING btree ("name");--> statement-breakpoint
CREATE INDEX "subscription_games_start_date_idx" ON "budget-gamer-next_subscription_games" USING btree ("start_date");--> statement-breakpoint
CREATE INDEX "subscription_games_end_date_idx" ON "budget-gamer-next_subscription_games" USING btree ("end_date");